merge_annots : en.all.align.ref.sec19_00-49.ali_annot cs.all.align.ref.sec19_00-49.ali_annot
en.all.align.ref.sec19_00-49.ali_annot : en_perspron/align.ref.sec19_00-49.all.ali_annot en_perspron_unexpr/align.ref.sec19_00-49.all.ali_annot en_relpron/align.ref.sec19_00-49.all.ali_annot en_cor/align.ref.sec19_00-49.all.ali_annot
	cat $^ > $@
cs.all.align.ref.sec19_00-49.ali_annot : cs_perspron/align.ref.sec19_00-49.all.ali_annot cs_perspron_unexpr/align.ref.sec19_00-49.all.ali_annot cs_relpron/align.ref.sec19_00-49.all.ali_annot cs_cor/align.ref.sec19_00-49.all.ali_annot
	cat $^ > $@
